In [1]:
import pandas as pd
import numpy as np
import os

In [11]:
processed_data_path = os.path.join(os.path.pardir,'data','processed')
train_file_path = os.path.join(processed_data_path, 'train.csv')
test_file_path = os.path.join(processed_data_path, 'test.csv')

In [12]:
train_df = pd.read_csv(train_file_path, index_col='PassengerId')
test_df = pd.read_csv(test_file_path, index_col='PassengerId')

In [13]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 33 columns):
Survived              891 non-null int64
Age                   891 non-null float64
Fare                  891 non-null float64
FamilySize            891 non-null int64
IsMother              891 non-null int64
IsMale                891 non-null int64
Deck_A                891 non-null int64
Deck_B                891 non-null int64
Deck_C                891 non-null int64
Deck_D                891 non-null int64
Deck_E                891 non-null int64
Deck_F                891 non-null int64
Deck_G                891 non-null int64
Deck_Z                891 non-null int64
Pclass_1              891 non-null int64
Pclass_2              891 non-null int64
Pclass_3              891 non-null int64
Title_Lady            891 non-null int64
Title_Master          891 non-null int64
Title_Miss            891 non-null int64
Title_Mr              891 non-null int64
Title_Mrs             891 non-

In [14]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 892 to 1309
Data columns (total 32 columns):
Age                   418 non-null float64
Fare                  418 non-null float64
FamilySize            418 non-null int64
IsMother              418 non-null int64
IsMale                418 non-null int64
Deck_A                418 non-null int64
Deck_B                418 non-null int64
Deck_C                418 non-null int64
Deck_D                418 non-null int64
Deck_E                418 non-null int64
Deck_F                418 non-null int64
Deck_G                418 non-null int64
Deck_Z                418 non-null int64
Pclass_1              418 non-null int64
Pclass_2              418 non-null int64
Pclass_3              418 non-null int64
Title_Lady            418 non-null int64
Title_Master          418 non-null int64
Title_Miss            418 non-null int64
Title_Mr              418 non-null int64
Title_Mrs             418 non-null int64
Title_Officer         418 n

In [18]:
X=train_df.loc[:,'Age':].as_matrix().astype('float')
y=train_df['Survived'].ravel()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [19]:
print(X.shape,y.shape)

(891, 32) (891,)


In [20]:
from sklearn.model_selection import train_test_split

In [23]:
X_train,X_test,y_train,y_test=train_test_split(X, y, test_size=0.2, random_state=0)

In [24]:
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(712, 32) (179, 32) (712,) (179,)


In [25]:
print('Mean survival in train:{0:.3f}'.format(np.mean(y_train)))
print('Mean survival in test:{0:.3f}'.format(np.mean(y_test)))

Mean survival in train:0.383
Mean survival in test:0.385


# Scikit-Learn

In [26]:
import sklearn

## Baseline Model

In [28]:
from sklearn.dummy import DummyClassifier

In [32]:
model_dummy=DummyClassifier(strategy='most_frequent', random_state=0)

In [33]:
model_dummy.fit(X_train,y_train)

DummyClassifier(constant=None, random_state=0, strategy='most_frequent')

In [34]:
print('Score of base line model:{0:.2f}'.format(model_dummy.score(X_test,y_test)))

Score of base line model:0.61


In [36]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score

In [37]:
print('Accuarcy of base line model:{0:.2f}'.format(accuracy_score(y_test,model_dummy.predict(X_test))))

Score of base line model:0.61


In [39]:
print('Consuion Matrix of base line model: \n{0}'.format(confusion_matrix(y_test,model_dummy.predict(X_test))))

Consuion Matrix of base line model: 
[[110   0]
 [ 69   0]]


In [41]:
print('Precision of base line model:{0:.2f}'.format(precision_score(y_test,model_dummy.predict(X_test))))
print('Recall of base line model:{0:.2f}'.format(recall_score(y_test,model_dummy.predict(X_test))))

Precision of base line model:0.00
Recall of base line model:0.00


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


## First Kaggle Submission

In [45]:
test_X=test_df.as_matrix().astype('float')

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [46]:
predictions=model_dummy.predict(test_X)

In [47]:
df_submission=pd.DataFrame({'PassengerId' : test_df.index, 'Survived' : predictions})

In [48]:
df_submission.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

In [49]:
submission_data_path=os.path.join(os.path.pardir,'data','external')
submission_file_path=os.path.join(submission_data_path,'01_dummy.csv')

In [50]:
df_submission.to_csv(submission_file_path, index=False)

In [52]:
def get_submission_file(model,filename):
    test_X=test_df.as_matrix().astype('float')
    predictions=model.predict(test_X)
    df_submission=pd.DataFrame({'PassengerId' : test_df.index, 'Survived' : predictions})
    submission_data_path=os.path.join(os.path.pardir,'data','external')
    submission_file_path=os.path.join(submission_data_path,filename)
    df_submission.to_csv(submission_file_path, index=False)
    


In [53]:
get_submission_file(model_dummy,'01_dummy.csv')

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


## Logistic Regression Model

In [54]:
from sklearn.linear_model import LogisticRegression

In [55]:
model_lr_1=LogisticRegression(random_state=0)

In [56]:
model_lr_1.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [57]:
print("Score for logistic regression-version 1 :{0:.2f}".format(model_lr_1.score(X_test,y_test)))

Score for logistic regression-version 1 :0.83


In [58]:
print('Accuarcy of base line model:{0:.2f}'.format(accuracy_score(y_test,model_lr_1.predict(X_test))))
print('Consuion Matrix of base line model: \n{0}'.format(confusion_matrix(y_test,model_lr_1.predict(X_test))))
print('Precision of base line model:{0:.2f}'.format(precision_score(y_test,model_lr_1.predict(X_test))))
print('Recall of base line model:{0:.2f}'.format(recall_score(y_test,model_lr_1.predict(X_test))))

Accuarcy of base line model:0.83
Consuion Matrix of base line model: 
[[95 15]
 [15 54]]
Precision of base line model:0.78
Recall of base line model:0.78


In [61]:
model_lr_1.coef_

array([[-0.02840734,  0.00455631, -0.50017004,  0.61922838, -0.81414743,
         0.12823264, -0.17253859, -0.39355488,  0.52215008,  1.09939125,
         0.40346551, -0.18369316, -0.30021028,  0.96558544,  0.48281794,
        -0.3451608 ,  0.28258585,  1.21850069,  0.56334183, -1.44612507,
         1.07146232, -0.11345497, -0.47306807,  0.16297326,  0.24746349,
         0.27998252,  0.4128233 ,  0.49202884,  0.46214499,  0.14906873,
         0.37253571,  0.73070686]])

In [63]:
get_submission_file(model_lr_1,'02_lr_1.csv')

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


## Hyper Parameter Optimization

In [64]:
model_lr=LogisticRegression(random_state=0)

In [65]:
from sklearn.model_selection import GridSearchCV

In [67]:
parameters={'C':[1.0, 10.0, 50.0, 100.0, 1000.0],'penalty':['l1','l2']}
clf=GridSearchCV(model_lr,param_grid=parameters,cv=3)

In [68]:
clf.fit(X_train,y_train)

GridSearchCV(cv=3, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [1.0, 10.0, 50.0, 100.0, 1000.0], 'penalty': ['l1', 'l2']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [70]:
clf.best_params_

{'C': 1.0, 'penalty': 'l1'}

In [76]:
print("Best Score :{0:.2f}".format(clf.best_score_))

Best Score :0.83


In [77]:
print('Score for logistic regression:{0:.2f}'.format(clf.score(X_test,y_test)))

Score for logistic regression:0.83


In [79]:
get_submission_file(clf,'03_lr.csv')

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


## Feature Normalization and Standardization

In [80]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

### Feature Nomalization

In [82]:
scaler=MinMaxScaler()
X_train_scaled=scaler.fit_transform(X_train)

In [87]:
X_train_scaled[:,0].min(), X_train_scaled[:,0].max()

(0.0, 1.0)

In [88]:
X_test_scaled=scaler.fit_transform(X_test)

### Feature standardization:

In [98]:
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.fit_transform(X_test)

### Create model after standardization

In [99]:
model_lr=LogisticRegression(random_state=0)
parameters={'C':[1.0, 10.0, 50.0, 100.0, 1000.0],'penalty':['l1','l2']}
clf=GridSearchCV(model_lr,param_grid=parameters,cv=3)
clf.fit(X_train_scaled,y_train)

GridSearchCV(cv=3, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [1.0, 10.0, 50.0, 100.0, 1000.0], 'penalty': ['l1', 'l2']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [100]:
clf.best_score_

0.8132022471910112

In [101]:
print('Logistic regresiion score:{0:.2f}'.format(clf.score(X_test_scaled,y_test)))

Logistic regresiion score:0.82


# Model Persistence

In [95]:
import pickle

In [96]:
model_file_path=os.path.join(os.path.pardir,'models','lr_model.pkl')
scaler_file_path=os.path.join(os.path.pardir,'models','lr_scaler.pkl')

In [97]:
model_file_pickle=open(model_file_path,'wb')
scaler_file_pickle=open(scaler_file_path,'wb')

In [102]:
pickle.dump(clf, model_file_pickle)
pickle.dump(scaler,scaler_file_pickle)

In [103]:
model_file_pickle.close()
scaler_file_pickle.close()

## Load the persisted file

In [108]:
model_file_pickle = open(model_file_path,'rb')
scaler_file_pickle = open(scaler_file_path,'rb')
clf_loaded=pickle.load(model_file_pickle)
scaler_loaded=pickle.load(scaler_file_pickle)
model_file_pickle.close()
scaler_file_pickle.close()

In [109]:
clf_loaded

GridSearchCV(cv=3, error_score='raise',
       estimator=LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': [1.0, 10.0, 50.0, 100.0, 1000.0], 'penalty': ['l1', 'l2']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [110]:
scaler_loaded

StandardScaler(copy=True, with_mean=True, with_std=True)

In [111]:
X_test_scaled = scaler_loaded.transform(X_test)

In [113]:
print('score for persisted model;{0:.2f}'.format(clf_loaded.score(X_test_scaled,y_test)))

score for persisted model;0.84
